"""
example_hf.py -- Demonstration of the core teaching Hartree-Fock code.

Three examples of increasing size:

  1. H2  at the textbook geometry (Szabo & Ostlund) -- checks correctness.
  2. H2O at the experimental geometry               -- classic reference.
  3. CH4 built automatically from SMILES by RDKit   -- the "real" workflow.

Literature RHF/STO-3G energies to compare against:
  H2  (R = 1.4 bohr):          E = -1.117  Hartree   (Szabo & Ostlund)
  H2O (experimental geometry): E = -74.96  Hartree
"""

import os
import sys

# Make the package importable when run as a script.
_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(_HERE)
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

from core import Molecule, rhf


def example_h2():
    """Hydrogen molecule at R = 0.74 Angstrom (about 1.4 Bohr)."""
    mol = Molecule.from_atoms(
        [("H", (0.0, 0.0, 0.0)),
         ("H", (0.0, 0.0, 1.4))],
        unit="bohr", name="H2 (R = 1.4 bohr)")
    return rhf(mol)


def example_h2o():
    """Water at the experimental geometry (r_OH = 0.9578 A, angle 104.478)."""
    mol = Molecule.from_atoms(
        [("O", (0.0000000,  0.0000000, 0.1173470)),
         ("H", (0.0000000,  0.7572260, -0.4693879)),
         ("H", (0.0000000, -0.7572260, -0.4693879))],
        unit="angstrom", name="H2O (experimental geometry)")
    return rhf(mol)


def example_ch4_from_smiles():
    """Methane: geometry generated by RDKit from the SMILES string 'C'."""
    mol = Molecule.from_smiles("C", name="CH4 (RDKit geometry)")
    return rhf(mol)


if __name__ == "__main__":
    results = {}
    for fn in (example_h2, example_h2o, example_ch4_from_smiles):
        print("\n" + "#" * 64)
        results[fn.__name__] = fn()

    print("\n" + "#" * 64)
    print("Summary of total RHF/STO-3G energies:")
    for name, res in results.items():
        print(f"  {name:28s} E = {res['energy']:16.10f} Hartree")
